# Generated by Django 5.1.2 on 2024-10-18 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_analysis', '0002_remove_salesrecord_created_remove_salesrecord_dated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesrecord',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
