# Generated by Django 5.1.1 on 2024-10-21 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_analysis', '0005_delete_team'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='salesrecord',
            unique_together={('employee_name', 'created_at')},
        ),
    ]
